### ISSUE TITLE
Photo does not show up well in mobile

### ISSUE THREAD

**Issue by Pat-Lafon** [reikdas/reikdas.github.io#2] opened 2023-09-08 20:18 UTC
Your photo is stretched in certain cases(as title).

**Comment by reikdas** [comment] 2023-09-08 21:25
The problem isn't mobile. The image gets skewed in Safari. Would appreciate a fix if you can.

**Comment by Pat-Lafon** [comment] 2023-09-08 21:27
Unfortunately I don't have the time to dive into the differences in javascript/css rendering between browsers at the moment.

**Comment by reikdas** [comment] 2023-09-08 21:28
Pls

**Comment by reikdas** [comment] 2023-09-15 15:34
Fixed in f24fd79d085e5fc5229e2379b5ca9852bdbcd840

**Closed as completed by reikdas** 2023-09-15 15:34 UTC
